url: "https://etnorozrabiaka.art" # the base hostname & protocol for your site, e.g. http://example.com
baseurl: "" # the subpath of your site, e.g. /blog
title: "Etnorozrabiaka" # the name of your site, e.g. ACME Corp.

permalink: /:categories/:year/:month/:day/:title

kramdown:
  input: GFM
  hard_wrap: true

collections:
  - lyrics
  - tributes

exclude:
  - LICENSE
